name: Build a Pelican Website
on:
  push:
  workflow_dispatch:
env:
  TARGET: test99
jobs:
  build-pelican1:
    runs-on: ubuntu-latest
    concurrency: # target must not be updated by two jobs at once
      group: testsite-${TARGET} # must agree with TARGET
    steps:
      - name: Checkout the test site
        run: |
          echo ${TARGET}
          sleep 10
          echo Done
  build-pelican2:
    runs-on: ubuntu-latest
    concurrency: # target must not be updated by two jobs at once
      group: testsite-${TARGET} # must agree with TARGET
    steps:
      - name: Checkout the test site
        run: |
          echo ${TARGET}
          sleep 10
          echo Done
