name: Build a Pelican Website
on:
  push:
    paths:
      - '**/build-pelican.yml'
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: |
          echo ${{ github.ref_name }}
          echo "test=$(echo ${{ github.ref_name }} | tr / -)" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: artifact2
          path: .
  # job2:
  #   needs: job1
  #   runs-on: ubuntu-latest
  #   concurrency: # target must not be updated by two jobs at once
  #     group: testsite-${{needs.job1.outputs.output1}} # must agree with TARGET
  #   steps:
  #     - env:
  #         OUTPUT1: ${{needs.job1.outputs.output1}}
  #       run: |
  #         echo "$OUTPUT1"
  #         echo ${{needs.job1.outputs.output1}}
  #         echo ${{ github.ref_name }}
