name: test temp
on:
  push:
  workflow_dispatch:
jobs:
  build-pelican:
    runs-on: ubuntu-latest
    steps:
      - name: Should fail
        uses: sebbASF/infra-actions/pelican@temp
        with:
          destination: xyz
