name: Build a Pelican Website
on:
  push:
  workflow_dispatch:
env:
  TARGET: test99
jobs:
  build-pelican:
    runs-on: ubuntu-latest
    concurrency: # target must not be updated by two jobs at once
      group: testsite-${{ env.TARGET }} # must agree with TARGET
    steps:
      - name: Checkout the test site
        run: echo ${TARGET}
